name: CI/CD Pipeline

on:
  push:
    branches:
      - main



jobs:
  trigger-module-rest: # moduleA 혹은 moduleC 에 변경사항이 발생한 경우
#    rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # 직전 커밋까지 가져오기
      - name: ready
        id : changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
      - name: check
        run: |
          echo "${{ env.changed_files }}"
      - name: Trigger Jenkins Job for Module A
        if: ${{ contains(env.changed_files, 'src/module-rest/')
          || contains(env.changed_files, 'src/module-sub-rest/')
          || contains(env.changed_files, 'src/module-common/')
          || contains(env.changed_files, '.github/')
          || contains(env.changed_files, 'gradle/')
          || contains(env.changed_files, 'gitattributes')
          || contains(env.changed_files, '.gitignore')
          || contains(env.changed_files, 'build.gradle')
          || contains(env.changed_files, 'gradlew')
          || contains(env.changed_files, 'gradlew.bat')
          || contains(env.changed_files, 'settings.gradle') }}
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins-ci-3s6ma465.autowini.com/"
          user: "uhyeon.jeon"
          token: "11522bf1954299cbb35df9b8c333ed4d89"
          job: "multi-module-test"
      - name: Trigger Jenkins Job for Module B
        if: ${{ contains(env.changed_files, 'src/module-websocket/')
          || contains(env.changed_files, 'src/module-sub-socket/')
          || contains(env.changed_files, 'src/module-common/')
          || contains(env.changed_files, '.github/')
          || contains(env.changed_files, 'gradle/')
          || contains(env.changed_files, 'gitattributes')
          || contains(env.changed_files, '.gitignore')
          || contains(env.changed_files, 'build.gradle')
          || contains(env.changed_files, 'gradlew')
          || contains(env.changed_files, 'gradlew.bat')
          || contains(env.changed_files, 'settings.gradle') }}
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins-ci-3s6ma465.autowini.com/"
          user: "uhyeon.jeon"
          token: "11522bf1954299cbb35df9b8c333ed4d89"
          job: "multi-module-test"