name: CI/CD Pipeline

on:
  push:
    branches:
      - main



jobs:
  trigger-module-rest: # moduleA 혹은 moduleC 에 변경사항이 발생한 경우
#    rules:
    runs-on: ubuntu-latest
    steps:
      - name: ready

        run: |
          echo "ready"
          echo $(github.event.head_commit.modified)
      - name: Trigger Jenkins Job for Module A
        if: ${{ contains(github.event.head_commit.modified, 'src/module-rest/')
          || contains(github.event.head_commit.modified, 'src/module-sub-rest/')
          || contains(github.event.head_commit.modified, 'src/module-common/')
          || contains(github.event.head_commit.modified, '.github/')
          || contains(github.event.head_commit.modified, 'gradle/')
          || contains(github.event.head_commit.modified, 'gitattributes')
          || contains(github.event.head_commit.modified, '.gitignore')
          || contains(github.event.head_commit.modified, 'build.gradle')
          || contains(github.event.head_commit.modified, 'gradlew')
          || contains(github.event.head_commit.modified, 'gradlew.bat')
          || contains(github.event.head_commit.modified, 'settings.gradle') }}
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins-ci-3s6ma465.autowini.com/"
          user: "uhyeon.jeon"
          token: "11522bf1954299cbb35df9b8c333ed4d89"
          job: "multi-module-test"
      - name: Trigger Jenkins Job for Module B
        if: ${{ contains(github.event.head_commit.modified, 'src/module-websocket/')
          || contains(github.event.head_commit.modified, 'src/module-sub-socket/')
          || contains(github.event.head_commit.modified, 'src/module-common/')
          || contains(github.event.head_commit.modified, '.github/')
          || contains(github.event.head_commit.modified, 'gradle/')
          || contains(github.event.head_commit.modified, 'gitattributes')
          || contains(github.event.head_commit.modified, '.gitignore')
          || contains(github.event.head_commit.modified, 'build.gradle')
          || contains(github.event.head_commit.modified, 'gradlew')
          || contains(github.event.head_commit.modified, 'gradlew.bat')
          || contains(github.event.head_commit.modified, 'settings.gradle') }}
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins-ci-3s6ma465.autowini.com/"
          user: "uhyeon.jeon"
          token: "11522bf1954299cbb35df9b8c333ed4d89"
          job: "multi-module-test"