name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'module-common/**'
      - 'module-rest/**'
      - 'module-sub-rest/**'
      - '.github/**'
      - 'gradle/**'
      - '.gitattributes'
      - '.gitignore'
      - 'build.gradle'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle'

jobs:
  trigger-jenkins:
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
#          url: ${{ secrets.JENKINS_URL }}
#          user: ${{ secrets.JENKINS_USER }}
#          token: ${{ secrets.JENKINS_TOKEN }}
#          job: "my-pipeline-job"
          url: "https://jenkins-ci-3s6ma465.autowini.com"
          user: "uhyeon.jeon"
          token: "multi-module-test"
          job: "multi-module-test"
